---
title: "Module 2: Data structure and formats"
format: html
---

::: {.callout-note}
# Relevant learning standards
1. Classify variables by measurement type (nominal, ordinal, interval, ratio) and justify those classifications with reference to the characteristics of the data. (Lab 1)
2. Distinguish between vector and raster formats with spatial data.
:::


::: {.required-actions}
# Required on day 1 

## Videos
- [Nominal, Ordinal, Interval, and Ratio Data (Grad Coach)](https://www.youtube.com/watch?v=5Yh-9xdJzAs){target="_blank"}
- [Data types in R programming](https://www.youtube.com/watch?v=VtUVQWl0aRA&t){target="_blank"} by R Programming 101
- [Vector vs Raster Data in GIS (Felt)](https://www.youtube.com/watch?v=N-3zF10LbHg){target="_blank"}


## Readings
- [Levels of Measurement (LibreTexts)](https://stats.libretexts.org/Workbench/Statistics_for_Behavioral_Science_Majors/01%3A_Naming_Collecting_Data_and_Research_Design/1.04%3A_Levels_of_Measurement){target="_blank"}
- [Types of Objects in R](https://dshizuka.github.io/RCourse/02_ObjectTypes.html){target="_blank"} by Dai Shizuka, *Intro to R*
::: 

# Course materials { .module-section }

## Scripts
* [S03: APIs and online data](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/.scripts/geog4300_S03%20APIs%20and%20online%20data.qmd){target="_blank"}
* [S04: Vectors, lists, and data frames](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/.scripts/geog4300_S04%20Vectors%20lists%20and%20data%20frames%20oh%20my.qmd){target="_blank"}

## Slides for class
* [L04-Reading data](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/in_class_slides/geog4300_L04-readingdata.pptx){target="_blank"}
* [L05-Spatial data](https://github.com/communitymaplab/geog4300_datascience/raw/refs/heads/main/in_class_slides/geog4300_L05-spatialdata.pptx){target="_blank"}

# Additional Resources {.module-section}

## Readings
- [Geospatial Data Types (Geoapify)](https://www.geoapify.com/different-geospatial-data-types/){target="_blank"}
- [Geocomputation with R](https://r.geocompx.org/spatial-class){target="_blank"}, Chap. 2: Geographic Data in R
- [R for Psychological Science](https://rstudio-education.github.io/hopr/r-objects.html){target="_blank"}: Chapter 13, R data types

## Videos
* [Vectors, data frames, and lists (Ben Stenhaug)](https://www.youtube.com/watch?v=XHAm_V-KZE8){target="_blank"}
* [Vector vs Raster Data - GIS Explained (Mr Cognito)](https://www.youtube.com/watch?v=3DVgQFALxCo){target="_blank"}
* TBD on Simple features