project:
  type: website
  output-dir: docs

website:
  title: "Data Science in Geography (Geog4/6300)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: modules/index.qmd
        text: Course modules
      - href: course_data.qmd
        text: Course data
      - href: labs.qmd
        text: Course labs
      - href: learning_standards.qmd
        text: Learning standards
      - href: resources.qmd
        text: Resources


    right:
      - icon: github
        href: https://github.com/communitymaplab/geog4300_datascience
        aria-label: GitHub

  sidebar:
    - id: modules-sidebar
      title: "Course Modules"
      style: docked
      search: true
      contents:
        - href: modules/index.qmd
          text: Module overview
        - href: modules/m1_introduction.qmd
          text: Module 1-Introduction to R
        - href: modules/m2_datastructure.qmd
          text: Module 2-Data Structure and Formats
        - href: modules/m3_datawrangling.qmd
          text: Module 3-Data wrangling
        - href: modules/m4_data_visualize.qmd
          text: Module 4-Descriptive statistics and visualization
        - href: modules/m5_spatial_describe.qmd
          text: Module 5-Descriptive spatial statistics
        - href: modules/m6_inferential stats.qmd
          text: Module 6-Inferential statistics
        - href: modules/m7_tests_difference.qmd
          text: Module 7-Tests of difference
        - href: modules/m8_tests_association.qmd
          text: Module 8-Tests of association

format:
  html:
    theme:
      - spacelab
    css: styles.css
    toc: true



