---
title: "Geog4/6300: Data Science in Geography"
author:
  - "Dr. Jerry Shannon"
  - "Dr. Anna Harper"
language:
  title-block-author-plural: "Authors"
subtitle: "University of Georgia, Fall 2026"
---

# Welcome

Welcome to the online site for Geog4/6300: Data Science in Geography. This course is offered each fall within the University of Georgia's Department of Geography. It provides a review/introduction to both geostatistical analysis and to using a code-based approach (specifically using R) for doing quantitative research. 

This course is NOT a GIS class, but we will cover how to load and work with spatial data and use elements of spatial analysis. It spends more time on data cleaning and manipulation that most GIS coursework as well as reviewing statistical techniques such as tests of difference and regression modeling.

::: {.required-actions}
# Before you start 

Download and install the following

- [The R software package](https://cran.r-project.org/bin/windows/base/){target="_blank"}
- [The RStudio IDE](https://posit.co/downloads){target="_blank"}
- [Git](https://git-scm.com/install/){target="_blank"} (not required but recommended)
- [Github Desktop](https://desktop.github.com/download/){target="_blank"} (not required but recommended)

You should also create [an account on Github](https://www.github.com){target="_blank"} if you don't already have one.
::: 

# Course objectives and learning standards

The main objectives of the course are as follows:

  1. Understand basic concepts and methods of data collection and description
  2. Understand basic concepts of mathematical probability theory
  3. Understand the logic and practice of simple inferential statistics
  4. Understand correlation and regression analysis
  5. Ability to use appropriate statistical techniques in tackling geographical problems.
  6. Ability to comprehend academic literature that uses statistical techniques.

A more detailed list of skills that students will demonstrate through their coursework is available [on this learning standards page](learning_standards.qmd).

# Where to find things

- The [course syllabus](https://docs.google.com/document/d/1C1GHXTsvwvRl92LuJcXnIIgqvD3WQ9tmZ1REM0LTE_I/edit?usp=drive_link){target="_blank"} and [schedule](https://docs.google.com/spreadsheets/d/1kkK6xVx-wwIya_0yzGHPzkEqEGFJWAxO41vaOcfqs4Y/edit?usp=drive_link){target="_blank"} are both hosted on Google Drive. Click the links to find those. 
- The main content of the course is broken into [modules](modules/index.qmd), and this site will provide a page with resources relevant to each of them. This includes links to relevant scripts and datasets used in class. These are also available on the Github repository linked to this site. Click the Github link in the top menu bar for another way to find those.
- For lab assignments, you will be creating a "fork" of a master lab repository on Github--creating your own copy. Once you are finished, you'll submit a link to that repository on ELC. Click on the Labs link in the top menu bar to see links to the master lab templates.
- [ELC](https://elc.uga.edu){target="_blank"} will be the place to go for recordings of our class sessions as well as things related to assessment.
- The [Resources](resources.qmd) page of this site has multiple online guides to help support your work and learning.
- We will also often be using the [Tidy Tuesday](https://github.com/rfordatascience/tidytuesday){target="_blank"} repository for in-class activities and group work.
